name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # matches local venv recommendation
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run tests (pytest)
        run: |
          pytest -q

      - name: Import smoke (fallback)
        if: ${{ failure() }}
        run: |
          python - << 'PY'
import importlib
mods = ["pandas","numpy","yfinance","statsmodels","pmdarima","sklearn","tensorflow","pypfopt","matplotlib","scipy","tqdm"]
for m in mods:
    importlib.import_module(m)
print("Imports OK")
PY
